[package]
name = "rjit"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2"
memmap = "0.7.0"
memmap2 = "0.5.0"
libc = "0.2.112"